name: Build_Finder_APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔥 Python 3.10 (مهم‌ترین بخش)
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            python3-venv \
            zip \
            unzip \
            git \
            libffi-dev \
            libssl-dev \
            libncurses6 \
            libncurses-dev \
            zlib1g-dev \
            libsqlite3-dev

      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Finder-APK
          path: bin/*.apk

